#!/bin/bash
# Bu betik, belirtilen portlari açik birakacak şekilde ufw kurallarini ayarlar.
# Bu komutlar sadece root (sudo) yetkileri ile çaliştirilabilir.
if [ "$EUID" -ne 0 ]; then
  echo "Bu scripti çaliştirmak için root (sudo) yetkilerine sahip olmalisiniz."
  exit 1
fi
# UFW'yi etkinleştir
ufw enable
# Etkinleştirilmiş tüm ufw kurallarini temizle (mevcut kurallari kaldirmak için)
ufw --force reset
# Kapatmak veya açmak istediğiniz portlari buraya ekleyin.
# Örnek: Kapatmak istediğiniz portlar -> PORTS_TO_DENY=(53 80)
#        Açmak istediğiniz portlar -> PORTS_TO_ALLOW=(8080 9000)
PORTS_TO_DENY=(32768) 
declare -a PORTS_TO_ALLOW=("21" "22" "25" "53" "106" "110" "143" "465" "953" "993" "995" "3030" "3306" "4190" "7080" "7081" "8443" "8880" "12346" "12768" "35799" "40785")
# Bağlantilari kaptmak için döngü
for port in "${PORTS_TO_DENY[@]}"
do
  echo "Port $port kapatiliyor..."
  ufw deny "$port"/tcp
  ufw deny "$port"/udp
done
# Bağlantilari eklemek için döngü
for port in "${PORTS_TO_ALLOW[@]}"
do
    # TCP bağlantilari
    ufw allow $port/tcp  
done
ufw allow 53/udp
# UFW'yi yeniden yükle
ufw reload
ufw enable
ufw status
echo "UFW kurallari başariyla güncellendi."